server:
  port: 5000

app:
  email: ahmed83@me.com
  datasource:
    jdbc-url: jdbc:postgresql://db:5432/webshop3d
    username: postgres
    password: password
    pool-size: 30

# AWS S3 configuration
aws:
  access_key_id: ''
  secret_access_key: ''
  s3:
    bucket: ''
    region: ''

# JWT configuration
application:
  jwt:
    secretKey: ENC(kAiWeUmRNeAp5Z6ExN7byeSUHwUWtlL2llIlFG3UTVdCIRLvVIQVaYrYrD6mwU72nZoKGP0Nzc0=)
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14
