server:
  port: 5000

app:
  email-contactus: ahmed83@me.com
  email-extra-contactus: ahmed83@me.com
  email-order: ahmed83@me.com
  datasource:
    jdbc-url: ENC(0X7QP5t42RXo/W0NOpF855u9ZFQt16Oe0ylZbR9MlPjLau/kCPPKabnef/+Zn04ZlzCHtRlWZ4VRXCQ1haPpfPPHFc2wlWBBc9hX/ac0KjOkXAxgtBPcD1h2DK1bfUSTQBX5xcXpxuk=)
    username: ENC(I+6UelmTVFkerKIJVjlzFv/2/g9H41Fc)
    password: ENC(T7LSZONtn7VK1GjSKP5MsBsQhL+aiSOZhgk0m49rOVA=)
    pool-size: 30

# AWS S3 configuration
aws:
  access_key_id: ENC(eqWStuJmMS4G1L7FZ17TnNFTGhov87k2qxkpwriNtlM=)
  secret_access_key: ENC(YZp7ucNeP/gT/2tE7yH5yqM1HClLgpc1aZP1q0slPWsLt0Gmj02zL3bBmElEFWTXqEtYjYPHfZI=)
  s3:
    bucket: ENC(1Or2IJt0D/K6u5jVosq6+rWFtALnBfHoLVflKBUS2xQ=)
    region: ENC(z2xSNPE0m5JVkERUF09PUWtaeI5iEn7Z)
  dynamo_db:
    access_key_id: ENC(IXIMJvhCitpBrS/pmGBLacPScTemkTn9UvDZ67IoWv0=)
    secret_access_key: ENC(pedEx1IAGLMEzShdKLqbCV6+Bcsbvh8b+Vc+KSTLqGKN3qWn/XpPdRq3jPX+RWeKCzQnKoi0fWE=)

# JWT configuration
application:
  jwt:
    secretKey: ENC(kAiWeUmRNeAp5Z6ExN7byeSUHwUWtlL2llIlFG3UTVdCIRLvVIQVaYrYrD6mwU72nZoKGP0Nzc0=)
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14

spring:
  flyway:
    out-of-order: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 3d.electronics.iraq@gmail.com
    password: ENC(a7pCrmsh5/BW5oqczZ/qosu9QQJpJHQtPYpqE8V2nIA=)
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 500
          starttls:
            enable: true