server:
  port: 5000

app:
  email: ahmed83@me.com
  datasource:
    jdbc-url: jdbc:postgresql://db:5432/webshop3d
    username: postgres
    password: password
    pool-size: 30

# AWS S3 configuration
aws:
  access_key_id: ''
  secret_access_key: ''
  s3:
    bucket: ''
    region: ''

# JWT configuration
application:
  jwt:
    secretKey: '%?ANZ!yR>%*]hV~,&k!x5z24m7Cw4+<Cc_m-/</N-8?zPLd'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14
