server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: test
  flyway:
    enabled: false

  application:
    name: 3D Webshop

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: HSQL
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

  datasource:
    jdbcUrl: jdbc:hsqldb:mem:webshop3d
    driverClassName: org.h2.Driver
    username: sa
    password:

application:
  jwt:
    secretKey: 'testsecuretestsecuretestsecuretestsecuretestsecuretestsecure'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14

