server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost/webshop3d
    username: postgres
    password: password
    pool-size: 30

# AWS S3 configuration
aws:
  access_key_id: 'AKIAIW6DFGN33INHDGLQ'
  secret_access_key: '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'
  s3:
    bucket: '3d-iraq.com'
    region: 'me-south-1'

# JWT configuration
application:
  jwt:
    secretKey: '%?ANZ!yR>%*]hV~,&k!x5z24m7Cw4+<Cc_m-/</N-8?zPLd'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14