server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost/webshop3d
    username: postgres
    password: password
    pool-size: 30

application:
  jwt:
    secretKey: '%?ANZ!yR>%*]hV~,&k!x5z24m7Cw4+<Cc_m-/</N-8?zPLd'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14