server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev

  application:
    name: 3D Webshop
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB

application:
  properties:
    imageBucketLink: 3d-webshop-upload-image