server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost/webshop3d
    username: postgres
    password: password
    pool-size: 30

# AWS S3 configuration
aws:
  endpointUrl: 'https://s3.us-east-2.amazonaws.com'
  access_key_id: 'AKIA25AXLWROY7Z4M6FZ'
  secret_access_key: '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'
  s3:
    bucket: '3d-iraq-products-images'
    region: 'me-south-1'

# JWT configuration
application:
  jwt:
    secretKey: '%?ANZ!yR>%*]hV~,&k!x5z24m7Cw4+<Cc_m-/</N-8?zPLd'
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14